// One UI dictionary keeps the interface language separate from weather data.
// English remains the safe fallback until a provider returns a regional-language answer.
const _hi = <String, String>{
  'good_morning': 'सुप्रभात! 👋',
  'overview': 'यहाँ आपके मौसम का विवरण है',
  'weather_details': 'मौसम विवरण',
  'rain_check': 'बारिश की जानकारी',
  'seven_day_forecast': '7-दिन का पूर्वानुमान',
  'weather_alerts': 'मौसम चेतावनियाँ',
  'ask_weathergpt': 'WeatherGPT से पूछें',
  'explore_more': 'और जानें',
  'use_gps': 'GPS का उपयोग करें',
  'using_current_location': 'आपके वर्तमान स्थान का उपयोग हो रहा है',
  'location_not_connected':
      'स्थान कनेक्ट नहीं है — “मेरे पास” पूछने पर GPS मांगा जाएगा।',
  'advice_for': 'सलाह किसके लिए:',
  'everyone': 'सभी के लिए',
  'traveller': 'यात्री',
  'farmer': 'किसान',
  'student': 'विद्यार्थी',
  'outdoor_worker': 'बाहरी काम करने वाला',
  'commuter': 'दैनिक यात्री',
  'ask_anything': 'कुछ भी पूछें',
  'chat_greeting':
      'नमस्ते! मैं WeatherGPT हूँ। आज के मौसम, बारिश या पूर्वानुमान के बारे में पूछें।',
  'weather_details_prompt': 'मौसम विवरण',
  'rain_check_prompt': 'बारिश की जानकारी',
  'forecast_prompt': '7-दिन का पूर्वानुमान',
  'live_data': 'Open-Meteo से लाइव डेटा',
  'live_weather_used': 'लाइव मौसम डेटा इस्तेमाल किया गया',
  'fallback_notice': 'लाइव मौसम डेटा से उत्तर दिया गया',
  'forecast_will_appear': 'लाइव डेटा आने पर पूर्वानुमान दिखाई देगा।',
  'weather_risk': 'मौसम जोखिम',
  'recommended_action': 'अनुशंसित कार्रवाई',
  'decision_confidence': 'निर्णय का भरोसा',
  'why': 'क्यों?',
  'why_this_decision': 'यह निर्णय क्यों?',
  'risk_breakdown': 'जोखिम विवरण',
  'evidence': 'सबूत',
  'source': 'स्रोत',
  'close': 'बंद करें',
  'no_alerts': 'अभी कोई आधिकारिक मौसम चेतावनी कनेक्ट नहीं है।',
  'alerts_subtitle':
      'किसी आधिकारिक स्रोत के जुड़ने पर चेतावनियाँ यहाँ दिखाई देंगी।',
  'rain_now': 'अभी बारिश',
  'humidity': 'नमी',
  'wind': 'हवा',
  'today': 'आज',
  'rain': 'बारिश',
  'peak': 'सबसे अधिक जोखिम',
  'carry': 'साथ रखें',
  'avoid': 'बचें',
  'precautions': 'सावधानियाँ',
  'why_label': 'कारण',
  'allow_location': 'स्थान की अनुमति दें',
  'not_now': 'अभी नहीं',
  'choose_language': 'उत्तर की भाषा चुनें',
  'response_language_subtitle': 'WeatherGPT आपके उत्तर इस भाषा में देगा।',
  'continue': 'जारी रखें',
  'settings_language': 'भाषा बदलें',
  'view_all': 'सभी देखें',
  'ask_now': 'अभी पूछें',
  'feels_like': 'महसूस हो रहा है',
};

String uiText(String code, String key) =>
    code == 'hi' ? (_hi[key] ?? _english[key] ?? key) : (_english[key] ?? key);

const _english = <String, String>{
  'good_morning': 'Good morning! 👋',
  'overview': 'Here’s your weather overview',
  'weather_details': 'Weather details',
  'rain_check': 'Rain check',
  'seven_day_forecast': '7-day forecast',
  'weather_alerts': 'Weather alerts',
  'ask_weathergpt': 'Ask WeatherGPT',
  'explore_more': 'Explore more',
  'use_gps': 'Use GPS',
  'using_current_location': 'Using your current location',
  'location_not_connected':
      'Location not connected — GPS will be requested for “near me”.',
  'advice_for': 'Advice for:',
  'everyone': 'Everyone',
  'traveller': 'Traveller',
  'farmer': 'Farmer',
  'student': 'Student',
  'outdoor_worker': 'Outdoor worker',
  'commuter': 'Commuter',
  'ask_anything': 'Ask anything',
  'chat_greeting':
      'Hi! I’m WeatherGPT. Ask me about today’s weather, rain, or the forecast.',
  'weather_details_prompt': 'Weather details',
  'rain_check_prompt': 'Rain check',
  'forecast_prompt': '7-day forecast',
  'live_data': 'Live data from Open-Meteo',
  'live_weather_used': 'Live weather data used',
  'fallback_notice': 'Answer generated using live weather data',
  'forecast_will_appear': 'Forecast will appear when live data loads.',
  'weather_risk': 'WEATHER RISK',
  'recommended_action': 'Recommended action',
  'decision_confidence': 'Decision confidence',
  'why': 'WHY?',
  'why_this_decision': 'Why this decision?',
  'risk_breakdown': 'Risk breakdown',
  'evidence': 'Evidence',
  'source': 'Source',
  'close': 'Close',
  'no_alerts': 'No official weather alerts are connected yet.',
  'alerts_subtitle':
      'Alerts will appear when an authoritative provider is configured.',
  'rain_now': 'Rain now',
  'humidity': 'Humidity',
  'wind': 'Wind',
  'today': 'Today',
  'rain': 'rain',
  'peak': 'Peak',
  'carry': 'Carry',
  'avoid': 'Avoid',
  'precautions': 'Precautions',
  'why_label': 'Why',
  'allow_location': 'Allow Location',
  'not_now': 'Not Now',
  'choose_language': 'Choose your response language',
  'response_language_subtitle':
      'WeatherGPT will use this language for its answers.',
  'continue': 'Continue',
  'settings_language': 'Change language',
  'view_all': 'View all',
  'ask_now': 'Ask now',
  'feels_like': 'Feels like',
};

String profileLabel(String code, String profile) => uiText(
    code,
    switch (profile) {
      'traveller' => 'traveller',
      'farmer' => 'farmer',
      'student' => 'student',
      'outdoor_worker' => 'outdoor_worker',
      'commuter' => 'commuter',
      _ => 'everyone'
    });
